version: '3'

networks:
  nordspace:
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET}

volumes:
  nordspace-volume:
    driver: local

services:
  database:
    container_name: nordspace_db
    env_file:
      - .env
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      SERVICE_NAME: mysql
    volumes:
      - nordspace-volume:/var/lib/mysql
    networks:
      - nordspace

  app-main:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/app-main/Dockerfile
    restart: unless-stopped
    privileged: true
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/app-main/php.ini:/usr/local/etc/php/php.ini
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - database
    networks:
      - nordspace